### PR TITLE
Updated comments in serach.java file

### PR DESCRIPTION
**Pull request by Sunnamuri06**
Hi Sai Manikanta,

i have updated the search.java with a comment.

please review and approve.

Regards,
Sunnamuri.

### CODE REVIEW

**Comment by saimanikanta06** [comment]
Hi Sunnmauri,

Your comments looks good.

Please add more details to the comment.

Regards,
SaiManikanta.

**Comment by Sunnamuri06** [comment]
Hi Sai Manikanta,

i have added more details to the comment.

please review and approve.

Regards,
Sunnamuri.

**Comment by saimanikanta06** [comment]
Hi Sunnamuri,

Comments looks good and changes approved and merge changes to the master branch.

Regards,
Sai Manikanta.

**Comment by RevanthPasham** [comment]
ok

**Pull request merged**
